import '../../models/category.dart';
import '../../models/service_template.dart';
import '../enum/billing_cycle.dart';

final defaultCategories = [
  Category(
    name: 'Vêtements',
    iconName: 'checkroom',
    colorHex: '#E91E63',
    isDefault: true,
  ),
  Category(
    name: 'Nourriture',
    iconName: 'restaurant',
    colorHex: '#FF9800',
    isDefault: true,
  ),
  Category(
    name: 'Transport',
    iconName: 'directions_car',
    colorHex: '#2196F3',
    isDefault: true,
  ),
  Category(
    name: 'Divertissement',
    iconName: 'movie',
    colorHex: '#9C27B0',
    isDefault: true,
  ),
  Category(
    name: 'Santé',
    iconName: 'favorite',
    colorHex: '#F44336',
    isDefault: true,
  ),
  Category(
    name: 'Services publics',
    iconName: 'bolt',
    colorHex: '#FFC107',
    isDefault: true,
  ),
  Category(
    name: 'Éducation',
    iconName: 'school',
    colorHex: '#4CAF50',
    isDefault: true,
  ),
  Category(
    name: 'Voyage',
    iconName: 'flight',
    colorHex: '#00BCD4',
    isDefault: true,
  ),
  Category(
    name: 'Cadeaux',
    iconName: 'card_giftcard',
    colorHex: '#E91E63',
    isDefault: true,
  ),
  Category(
    name: 'Sport',
    iconName: 'fitness_center',
    colorHex: '#FF5722',
    isDefault: true,
  ),
  Category(
    name: 'Autres',
    iconName: 'more_horiz',
    colorHex: '#9E9E9E',
    isDefault: true,
  ),
];
final defaultServices = [
  // Divertissement
  ServiceTemplate(
    name: 'Netflix',
    category: 'Divertissement',
    suggestedPrice: 13.49,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/netflix.png',
  ),
  ServiceTemplate(
    name: 'Disney+',
    category: 'Divertissement',
    suggestedPrice: 8.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Amazon Prime Video',
    category: 'Divertissement',
    suggestedPrice: 6.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/prime_video.png',
  ),

  ServiceTemplate(
    name: 'Canal+',
    category: 'Divertissement',
    suggestedPrice: 22.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'OCS',
    category: 'Divertissement',
    suggestedPrice: 11.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Apple TV+',
    category: 'Divertissement',
    suggestedPrice: 6.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),

  // Musique & Audio
  ServiceTemplate(
    name: 'Spotify',
    category: 'Divertissement',
    suggestedPrice: 10.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/spotify.png',
  ),
  ServiceTemplate(
    name: 'Apple Music',
    category: 'Divertissement',
    suggestedPrice: 10.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Deezer',
    category: 'Divertissement',
    suggestedPrice: 10.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'YouTube Premium',
    category: 'Divertissement',
    suggestedPrice: 11.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/youtube.png',
  ),
  ServiceTemplate(
    name: 'Audible',
    category: 'Divertissement',
    suggestedPrice: 9.95,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),

  // Cloud & Stockage
  ServiceTemplate(
    name: 'iCloud+',
    category: 'Services publics',
    suggestedPrice: 0.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Google One',
    category: 'Services publics',
    suggestedPrice: 1.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/google_one.png',
  ),
  ServiceTemplate(
    name: 'Dropbox',
    category: 'Services publics',
    suggestedPrice: 11.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'OneDrive',
    category: 'Services publics',
    suggestedPrice: 2.00,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),


  // Sport & Fitness
  ServiceTemplate(
    name: 'Basic-Fit',
    category: 'Sport',
    suggestedPrice: 24.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Keep Cool',
    category: 'Sport',
    suggestedPrice: 29.90,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Fitness Park',
    category: 'Sport',
    suggestedPrice: 19.90,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),

  // Éducation & Productivité
  ServiceTemplate(
    name: 'ChatGPT Plus',
    category: 'Éducation',
    suggestedPrice: 20.00,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/chatgpt.png',
  ),
  ServiceTemplate(
    name: 'Duolingo Plus',
    category: 'Éducation',
    suggestedPrice: 6.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'LinkedIn Premium',
    category: 'Éducation',
    suggestedPrice: 29.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Babbel',
    category: 'Éducation',
    suggestedPrice: 9.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),

  // Transport
  ServiceTemplate(
    name: 'Amazon Prime',
    category: 'Transport',
    suggestedPrice: 6.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
    logoUrl: '/assets/logos/amazon_prime.png',
  ),
  ServiceTemplate(
    name: 'Navigo (Pass Navigo)',
    category: 'Transport',
    suggestedPrice: 75.20,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Vélib',
    category: 'Transport',
    suggestedPrice: 8.30,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
  // Gaming
  ServiceTemplate(
    name: 'PlayStation Plus',
    category: 'Divertissement',
    suggestedPrice: 8.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Xbox Game Pass',
    category: 'Divertissement',
    suggestedPrice: 12.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Nintendo Switch Online',
    category: 'Divertissement',
    suggestedPrice: 3.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),

  // Services publics
  ServiceTemplate(
    name: 'EDF',
    category: 'Services publics',
    suggestedPrice: 75.00,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'SFR Box',
    category: 'Services publics',
    suggestedPrice: 35.00,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Free Mobile',
    category: 'Services publics',
    suggestedPrice: 19.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Orange',
    category: 'Services publics',
    suggestedPrice: 22.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: true,
    isDefault: true,
  ),
  ServiceTemplate(
    name: 'Bouygues Telecom',
    category: 'Services publics',
    suggestedPrice: 24.99,
    suggestedCycle: BillingCycle.monthly,
    isPopular: false,
    isDefault: true,
  ),
];
